version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package_manager: "ruby:bundler"
    directory: "/"
    schedule:
      interval: "daily"
